# Generated by Django 3.1.4 on 2020-12-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='isFavorite',
            field=models.BooleanField(default=False),
        ),
    ]
