# Generated by Django 3.1.4 on 2020-12-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_isfavorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='albumLogo',
            field=models.FileField(upload_to=''),
        ),
    ]
