# Generated by Django 3.1.4 on 2020-12-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20201229_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='fileType',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
